spring:
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test;  # 서버 모드
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated
  data:
    mongodb:
      uri: mongodb+srv://user1:1234@cluster-test-001.13kb6bi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-Test-001

  #  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#      location: /Users/User/Documents/filetest

  thymeleaf:
    cache: false  # 개발 중 캐시 비활성화, 배포 시에는 true로 설정
    mode: HTML  # 템플릿 모드, HTML5로 설정 가능하지만 Thymeleaf 3 이후 HTML이 권장됨
    encoding: UTF-8  # 템플릿 인코딩 설정
    servlet:
      content-type: text/html  # 콘텐츠 타입 설정
    prefix: classpath:/templates/  # 템플릿 파일 위치
    suffix: .html  # 템플릿 파일 확장자